[[plugins]]
repo = 'JulesWang/css.vim'
hook_add = '''
  Autocmd Syntax css
    \  hi link cssError Normal
    \| hi link cssBraceError Normal
    \| hi link cssDeprecated Normal
'''

[[plugins]]
repo = 'othree/csscomplete.vim'

# PostCSS (Sugar)
[[plugins]]
repo = 'hhsnopek/vim-sugarss'
hook_add = '''
  Autocmd Syntax sugarss
    \  hi sssClass            guifg=#2B2B2B guibg=#F6F7F7 gui=bold
    \| hi sssElement          guifg=#2B2B2B guibg=#F6F7F7 gui=NONE
    \| hi sssProperty         guifg=#0050B0 guibg=#F6F7F7 gui=NONE
    \| hi sssPropertyOverride guifg=#999999 guibg=#F6F7F7 gui=NONE
    \| hi sssAbsoluteUnit     guifg=#A67F59 guibg=#F6F7F7 gui=NONE
'''
