[[plugins]]
repo = 'othree/html5.vim'
hook_add = '''
  Autocmd Syntax html
    \  hi! link htmlError    htmlTag
    \| hi! link htmlTagError htmlTag
'''

[[plugins]]
repo = 'gregsexton/MatchTag'
hook_add = '''
  Autocmd Syntax xml runtime ftplugin/xml.vim
  Autocmd Syntax twig,blade runtime ftplugin/html.vim

  AutocmdFT php
    \ Autocmd BufWinEnter <buffer> call RemoveMatchTagEvent()

  function! RemoveMatchTagEvent() abort
    if exists('#matchhtmlparen')
      augroup matchhtmlparen
        autocmd! * <buffer>
      augroup END
    endif
  endfunction
'''
