[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
hook_source = '''
  let g:tern#filetypes = []
  let g:deoplete#sources#ternjs#tern_bin = 'tern'
  let g:deoplete#sources#ternjs#docs = 1
  let g:deoplete#sources#ternjs#types = 1
'''

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_enable_es6 = 1
  let g:jsdoc_allow_input_prompt = 0
  let g:jsdoc_access_descriptions = 2
  let g:jsdoc_custom_args_hook = {
    \ '^e$':          {'type': ' {Event} '},
    \ 'str':          {'type': ' {String} '},
    \ '^arr$':        {'type': ' {Array} '},
    \ '^(i\|n)$':     {'type': ' {Number} '},
    \ '^(o\|obj)$':   {'type': ' {Object} '},
    \ '^(fn\|cb)$':   {'type': ' {Function} '},
    \ '^(el\|node)$': {'type': ' {Element} '},
    \ 'callback\|cb': {'type': ' {Function} ', 'description': 'Callback function'}
    \ }

  AutocmdFT javascript
    \  nmap <buffer> ,c <Plug>(jsdoc)
    \| nmap <silent> <buffer> ,C ?function<CR>:nohlsearch<CR><Plug>(jsdoc)
'''

[[plugins]]
repo = 'chemzqm/vim-jsx-improve'
hook_add = '''
  let g:javascript_plugin_jsdoc = 1

  Autocmd Syntax javascript
    \  hi jsBraces              guifg=#999999 gui=NONE
    \| hi jsFuncBraces          guifg=#999999 gui=NONE
    \| hi jsBrackets            guifg=#999999 gui=NONE
    \| hi jsParens              guifg=#999999 gui=NONE
    \| hi jsDestructuringBraces guifg=#999999 gui=NONE
    \| hi jsParensIfElse        guifg=#999999 gui=NONE
    \| hi jsGlobalNodeObjects   guifg=#4091bf gui=NONE
    \| hi jsImport              guifg=#1E347B gui=NONE
    \| hi jsFrom                guifg=#1E347B gui=NONE
'''
