[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  AutocmdFT json
    \ nnoremap <silent> <buffer> ,c :<C-u>let &l:conceallevel = (&l:conceallevel ==# 0 ? 2 : 0)<CR>
      \:echo printf(' Conceal mode: %3S (local)', (&l:conceallevel ==# 0 ? 'Off' : 'On'))<CR>

  Autocmd Syntax json
    \  syntax match jsonComment "//.\{-}$"
    \| hi link jsonComment Comment
'''
hook_source = '''
  let g:vim_json_warnings = 0
  let g:vim_json_syntax_concealcursor = 'n'
'''
