[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_func = 'tsuquyomi#'
hook_add = '''
  AutocmdFT typescript
    \ setlocal ballooneval balloonexpr=tsuquyomi#balloonexpr()
'''
hook_source = '''
  let g:tsuquyomi_disable_quickfix = 1
  let g:tsuquyomi_completion_detail = 1
'''
