[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
merged = 0
on_ft = 'markdown'
hook_post_update = '''
if executable('npm')
  call system(printf('cd %s && npm install --no-package-lock',
    \ expand(dein#get('markdown-preview.nvim').rtp . '/app')))
endif
'''
hook_source = '''
let g:mkdp_port = 3010
let g:mkdp_auto_start = 0
let g:mkdp_auto_close = 0
let g:mkdp_open_to_the_world = 0
'''
hook_post_source  = 'au! BufEnter *.{md,mkd,markdown,mdown,mkdn,mdwn}'

[plugins.ftplugin]
markdown = '''
nnoremap <silent> <buffer> ,p :<C-u>call mkdp#util#open_preview_page()<CR>
nnoremap <silent> <buffer> ,q :<C-u>call mkdp#util#stop_preview()<CR>
'''
