[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
hook_add = 'let g:pydocstring_enable_mapping = 0'

[plugins.ftplugin]
python = '''
nmap <buffer> ,c <Plug>(pydocstring)
'''
