[[plugins]]
repo = 'w0rp/ale'
on_fn = 'ale#'
hook_add = '''
  let g:ale_emit_conflict_warnings = 0

  nmap <silent> <Right> <Plug>(ale_next_wrap)
  nmap <silent> <Left>  <Plug>(ale_previous_wrap)

 Autocmd BufEnter,BufWrite,WinEnter,TextChanged,TextChangedI
 \ *.{rs}
  \ call ale#Queue(0, 'lint_file')

  Autocmd ColorScheme *
  \  hi ALEErrorSign   guifg=#2B2B2B guibg=#FFC08E gui=bold
  \| hi ALEWarningSign guifg=#2B2B2B guibg=#F2E8DF gui=bold
  \| hi ALEErrorLine   guifg=#2B2B2B guibg=#F2E8DF gui=NONE
  \| hi ALEWarningLine guifg=#2B2B2B guibg=#F2E8DF gui=NONE
'''
hook_source = '''
  let g:ale_echo_cursor = 1
  let g:ale_lint_on_save = 0
  let g:ale_lint_on_enter = 0
  let g:ale_lint_on_text_changed = 0
  let g:ale_sign_error = '->'
  let g:ale_sign_warning = '—'
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = ' %s'
  let g:ale_set_signs = 0
  let g:ale_sign_column_always = 0
  let g:ale_history_enabled = 0
  let g:ale_history_log_output = 0

  let g:ale_rust_rustc_options = '-Z no-codegen -A unused'

  let g:ale_linters = {
  \ 'rust': ['rustc']
  \ }
'''
