[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nx = '<Plug>'}
hook_add = '''
  nmap  q <Plug>(caw:range:toggle)
  xmap  q <Plug>(caw:hatpos:toggle)
  nmap ,f <Plug>(caw:jump:comment-prev)
  nmap ,F <Plug>(caw:jump:comment-next)
  nmap ,a <Plug>(caw:dollarpos:toggle)

  nnoremap <silent> <Plug>(caw:range:toggle) :<C-u>call <SID>cawRangeToggle()<CR>

  function! s:cawRangeToggle() abort
    if v:count > 1
      let winView = winsaveview()
      execute "normal V". (v:count - 1) ."j\<Plug>(caw:hatpos:toggle)"
      call winrestview(winView)
    else
      execute "normal \<Plug>(caw:hatpos:toggle)"
    endif
  endfunction
'''
hook_source = '''
  let g:caw_no_default_keymappings = 1
  let g:caw_hatpos_skip_blank_line = 1
  let g:caw_dollarpos_sp_left = repeat("\u0020", 2)
'''
