[[plugins]]
repo = 't9md/vim-choosewin'
on_map = {n = '<Plug>(choosewin)'}
hook_add = 'AutocmdFT vimfiler nmap <buffer> - <Plug>(choosewin)'
hook_source = '''
  let g:choosewin_label = 'WERABC'
  let g:choosewin_label_align = 'left'
  let g:choosewin_blink_on_land = 0
  let g:choosewin_overlay_enable = 2
  let g:choosewin_color_land = {'gui': ['#0000FF', '#F6F7F7', 'NONE']}
  let g:choosewin_color_label = {'gui': ['#FFE1CC', '#2B2B2B', 'bold']}
  let g:choosewin_color_label_current = {'gui': ['#CCE5FF', '#2B2B2B', 'bold']}
  let g:choosewin_color_other = {'gui': ['#F6F7F7', '#EEEEEE', 'NONE']}
  let g:choosewin_color_shade = {'gui': ['#F6F7F7', '#EEEEEE', 'NONE']}
  let g:choosewin_color_overlay = {'gui': ['#2B2B2B', '#2B2B2B', 'bold']}
  let g:choosewin_color_overlay_current = {'gui': ['#CCE5FF', '#CCE5FF', 'bold']}
'''
