[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_add = '''
  nnoremap <silent> ;d :<C-u>Defx<CR>
  nnoremap <silent> ;D :<C-u>Defx -auto-cd<CR>
  nnoremap <silent> <nowait> ` :<C-u>Defx `expand('%:p:h')` -search=`expand('%:p')`<CR>

  function! Defx_mappings() abort
    setlocal nobuflisted

    nnoremap <silent> <buffer> <expr> j line('.') ==# line('$') ? 'gg' : 'j'
    nnoremap <silent> <buffer> <expr> k line('.') ==# 1 ? 'G' : 'k'
    nnoremap <silent> <buffer> <expr> o defx#do_action('open')
    nnoremap <silent> <buffer> <expr> S defx#do_action('open', 'vsplit')
    nnoremap <silent> <buffer> <expr> p defx#do_action('open', 'pedit')
    nnoremap <silent> <buffer> <expr> q defx#do_action('quit')
    nnoremap <silent> <buffer> <expr> n defx#do_action('new_file')
    nnoremap <silent> <buffer> <expr> N defx#do_action('new_directory')
    nnoremap <silent> <buffer> <expr> d defx#do_action('remove_trash')
    nnoremap <silent> <buffer> <expr> r defx#do_action('rename')
    nnoremap <silent> <buffer> <expr> R defx#do_action('redraw')
    nnoremap <silent> <buffer> <expr> e defx#do_action('toggle_select')
    nnoremap <silent> <buffer> <expr> E defx#do_action('toggle_select') . 'j'
    nnoremap <silent> <buffer> <expr> A defx#do_action('toggle_select_all')
    nnoremap <silent> <buffer> <expr> c defx#do_action('cd', [getcwd()])
    nnoremap <silent> <buffer> <expr> C defx#do_action('cd', [getcwd()])
    nnoremap <silent> <buffer> <expr> i defx#do_action('cd', ['..'])
    nnoremap <silent> <buffer> <expr> h defx#do_action('cd', ['..'])
    nnoremap <silent> <buffer> <expr> l defx#do_action('open')
  endfunction

  " Tuning
  Autocmd BufEnter,WinEnter \[defx\] let &l:statusline = ' '
    \| setlocal cursorline nonu nornu nolist colorcolumn=
  Autocmd BufLeave,WinLeave \[defx\]
    \ setlocal nocursorline
  Autocmd FileType defx call Defx_mappings()
'''
