[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nnoremap <silent> ;g :<C-u>Denite grep<CR>
  nnoremap <silent> ;j :<C-u>Denite jump<CR>
  nnoremap <silent> `  :<C-u>Denite buffer -winheight=14<CR>
  nnoremap <silent> ;b :<C-u>Denite buffer -winheight=8<CR>
  nnoremap <silent> ;B :<C-u>Denite buffer<CR>
  nnoremap <silent> ;r :<C-u>Denite register -winheight=8 -mode=normal<CR>
  nnoremap <silent> ;f :<C-u>Denite file_rec -mode=normal<CR>
  nnoremap <silent> ;s :<C-u>Denite line -buffer-name=search -mode=insert<CR>
  nnoremap <silent> ;v :<C-u>DeniteCursorWord line -buffer-name=search -mode=normal<CR>

  Autocmd Syntax denite
    \  highlight! default link deniteStatusLinePath   StatusLine
    \| highlight! default link deniteStatusLineNumber StatusLine
'''
hook_source = 'source $VIMFILES/dein/plugins/denite.vim'

[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = 'let g:fruzzy#sortonempty = 0'
hook_post_update = 'call fruzzy#install()'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
hook_add = '''
  nnoremap <silent> ;y :<C-u>Denite neoyank -no-statusline -mode=normal<CR>
  nnoremap <silent> ;r :<C-u>Denite neoyank register -buffer-name=register<CR>
  xnoremap <silent> ;r :<C-u>Denite neoyank register -buffer-name=register -default-action=replace<CR>
'''
hook_source = '''
  let g:neoyank#limit = 64
  let g:neoyank#file = $CACHE . '/yank_file'
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
  let g:neomru#do_validate = 0
  let g:neomru#filename_format = ':.'
  let g:neomru#time_format = '%m.%d — %H:%M'
  let g:neomru#file_mru_limit = 128
  let g:neomru#file_mru_path = $CACHE . '/neomru/file'
  let g:neomru#file_mru_ignore_pattern = '\.\%(vimrc\|log\)$'
  let g:neomru#directory_mru_limit = 0
  let g:neomru#directory_mru_path = $CACHE . '/neomru/directory'

  nnoremap <silent> ;w :<C-u>Denite file_mru -matchers='matcher/project_files'<CR>
  nnoremap <silent> ;W :<C-u>Denite file_mru<CR>
'''
