[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = {x = '<Plug>(EasyAlign)'}
hook_add = 'vmap <Enter> <Plug>(EasyAlign)'
hook_source = '''
let g:easy_align_ignore_groups = ['Comment', 'String']
let g:easy_align_delimiters = {
  \   ':': {
  \     'pattern': ':',
  \     'left_margin': 0, 'right_margin': 1, 'stick_to_left': 1
  \   },
  \   },
  \   ']': {
  \     'pattern': '[[\]]',
  \     'left_margin': 0, 'right_margin': 0, 'stick_to_left': 0
  \   },
  \   ')': {
  \     'pattern': '[()]',
  \     'left_margin': 0, 'right_margin': 0, 'stick_to_left': 0
  \   },
  \   '/': {
  \     'pattern': '//\+\|/\*\|\*/',
  \     'ignore_groups': ['^\(.\(Comment\)\@!\)*$'],
  \     'delimiter_align': 'l'
  \   },
  \   '=': {
  \     'pattern': '===\|<=>\|=\~[#?]\?\|=>\|[:+/*!%^=><&|.-?]*=[#?]\?\|[-=]>\|<[-=]',
  \     'left_margin': 1, 'right_margin': 1, 'stick_to_left': 0
  \   },
  \   '>': {
  \     'pattern': '>>\|=>\|>'
  \   },
  \   'f': {
  \     'pattern': ' \(\S\+(\)\@=',
  \     'left_margin': 0, 'right_margin': 0
  \   },
  \   'd': {
  \     'pattern': ' \(\S\+\s*[;=]\)\@=',
  \     'left_margin': 0, 'right_margin': 0
  \   }
  \ }
'''
