[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'
on_func = 'gina#'
hook_add = '''
  nnoremap <silent> -c :<C-u>Gina commit<CR>
  nnoremap <silent> -b :<C-u>Gina branch<CR>
  nnoremap <silent> -s :<C-u>Gina status --short<CR>
  nnoremap <silent> -t :<C-u>Gina tag<CR>
  nnoremap <silent> -i :<C-u>Gina info<CR>
  nnoremap <silent> -l :<C-u>Gina log<CR>
  nnoremap <silent> -C :<C-u>Gina changes<CR>
'''
hook_source = '''
  let g:gina#command#status#use_default_mappings = 0

  call gina#custom#command#option(
  \ '/\%(status\|changes\)',
  \ '--ignore-submodules')

  call gina#custom#command#option(
  \ '/\%(status\|changes\|branch\|grep\|log\)',
  \ '--opener', 'vsplit'
  \)

  call gina#custom#execute(
  \ '/\%(status\|changes\|commit\|branch\|blame\|ls\|log\|grep\|tag\)',
  \ 'let &l:statusline = " "'
  \)

  " branch
  call gina#custom#mapping#nmap('branch', 'n', '<Plug>(gina-branch-new)')
  call gina#custom#mapping#nmap('branch', 'm', '<Plug>(gina-branch-move)')
  call gina#custom#mapping#nmap('branch', 'M', '<Plug>(gina-branch-move-force)')
  call gina#custom#mapping#nmap('branch', 'D', '<Plug>(gina-branch-delete)')
  call gina#custom#mapping#nmap('branch', 'r', '<Plug>(gina-branch-refrsh)')
  call gina#custom#mapping#nmap('branch', 'o', '<Plug>(gina-commit-checkout)')

  " status
  call gina#custom#mapping#nmap('status', 's', '<Plug>(gina-index-toggle)')

  " log
  call gina#custom#mapping#nmap('log', 'p', '<Plug>(gina-diff-preview)')

  AutocmdFT gina*,git
  \  nmap <silent> <buffer> q :<C-u>quit<CR>
  \| nmap <silent> <buffer> Q :<C-u>quit!<CR>

  Autocmd ColorScheme,syntax gina*
  \  hi AnsiColor1  guifg=#006633 gui=NONE
  \| hi AnsiColor2  guifg=#999999 gui=NONE
  \| hi AnsiColor3  guifg=#2B2B2B guibg=#FAE5E4 gui=NONE
  \| hi AnsiColor11 guifg=#999999 gui=NONE
  \| hi AnsiColor13 guifg=#0050B0 gui=NONE
  \| hi AnsiColor14 guifg=#BA4747 gui=NONE
'''
