[[plugins]]
repo = 'neomake/neomake'
on_func = 'neomake#'
on_cmd = 'Neomake'
hook_add = '''
  AutocmdFT javascript,rust,php,go,json
    \ nnoremap <silent> <buffer> ,w :<C-u>call neomake#Make(1)<CR>

  Autocmd ColorScheme,Syntax *
    \  hi NeomakeError guifg=#2B2B2B guibg=#ffe4e1 gui=NONE
'''
hook_source = 'source ~/vimfiles/dein/plugins/neomake.vim'
