[[plugins]]
repo = 'roxma/nvim-yarp'
hook_done_update = '''
  if executable('pip3')
    call system('pip3 install -q --upgrade pynvim')
  endif
'''
hook_add = "let g:python3_host_prog = exepath('python')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
