[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = {v = '<Plug>(operator-surround-'}
hook_add = '''
  vmap sa <Plug>(operator-surround-append)
  vmap sd <Plug>(operator-surround-delete)
  vmap sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'tyru/operator-reverse.vim'
depends = 'vim-operator-user'
on_map = {v = '<Plug>(operator-reverse-'}
hook_add = '''
  vmap <silent> sw <Plug>(operator-reverse-text)
  vmap <silent> sl <Plug>(operator-reverse-lines)
'''

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'
depends = 'vim-operator-user'
on_map = {n = '<Plug>(operator-flashy)'}
hook_add = '''
  nmap y <Plug>(operator-flashy)
  nmap Y <Plug>(operator-flashy)$
'''
hook_source = '''
  let g:operator#flashy#flash_time = 280
  let g:operator#flashy#group = 'Visual'
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_map = {nx = '<Plug>'}
hook_add = '''
  nmap ,d <Plug>Dsurround
  nmap ,i <Plug>Csurround
  nmap ,I <Plug>CSurround
  nmap ,t <Plug>Yssurround
  nmap ,T <Plug>YSsurround
  xmap ,s <Plug>VSurround
  xmap ,S <Plug>VgSurround

  for char in split('` '' \" ( ) { } [ ]')
    execute printf('nmap ,%s ,Iw%s', char, char)
  endfor | unlet char
'''
hook_source = 'let g:surround_no_mappings = 1'
