[[plugins]]
repo = 'AndrewRadev/sideways.vim'
on_func = 'sideways#'
hook_add = '''
  nnoremap <silent> <C-h> :<C-u>call sideways#MoveLeft()<CR>
  nnoremap <silent> <C-l> :<C-u>call sideways#MoveRight()<CR>
  nnoremap <silent> <S-h> :<C-u>call sideways#JumpLeft()<CR>
  nnoremap <silent> <S-l> :<C-u>call sideways#JumpRight()<CR>

  source ~/vimfiles/dein/plugins/sideways.vim
'''
hook_source = '''
  let g:loaded_sideways = 1
  let g:sideways_search_timeout = 0
  let g:sideways_skip_strings_and_comments = 1

  let g:sideways_definitions = [
    \   {
    \     'start': '(\_s*', 'end': ')',
    \     'delimiter': ',\_s*',
    \     'brackets': ['([{''"', ')]}''"'],
    \   },
    \   {
    \     'start': '\[\_s*', 'end': '\]',
    \     'delimiter': ',\_s*',
    \     'brackets': ['([{''"', ')]}''"'],
    \   },
    \   {
    \     'start': '{\_s*', 'end': '}',
    \     'delimiter': ',\_s*',
    \     'brackets': ['([{''"', ')]}''"'],
    \   },
    \ ]
'''
