[[plugins]]
repo = 'SirVer/ultisnips'
on_event = 'InsertCharPre'
on_ft = 'snippets'
hook_add = '''
Autocmd BufNewFile,BufReadPost *.snippets
  \ set filetype=snippets nowrap foldmethod=manual
'''
hook_post_source = '''
let g:UltiSnipsEnableSnipMate = 0
let g:UltiSnipsExpandTrigger = '<C-F12>'
let g:UltiSnipsListSnippets = '<C-F12>'
let g:UltiSnipsSnippetDirectories = [expand('$VIMFILES/snippets')]

imap `         <Plug>(ultisnips)
xmap `         <Plug>(ultisnipsVisual)
snoremap <C-c> <Esc>

inoremap <silent> <Plug>(ultisnips)        <C-r>=UltiComplete("\`")<CR>
xnoremap <silent> <Plug>(ultisnipsVisual) :<C-u>call UltiSnips#SaveLastVisualSelection()<CR>gvs

function! UltiComplete(key) abort
  if len(UltiSnips#SnippetsInCurrentScope()) > 0
    let curPos= getcurpos()[4]
    let hasBackspace = getline('.')[curPos-2] =~ '\s'
    let hasStartLine = curPos <= 1

    if !hasStartLine && !hasBackspace
      return UltiSnips#ExpandSnippet()
    endif
  endif

  return a:key
endfunction
'''

[ftplugin]
twig = '''
call UltiSnips#AddFiletypes('twig.html')
'''
blade = '''
call UltiSnips#AddFiletypes('blade.html')
'''
